# Generated by Django 5.2.10 on 2026-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("title", models.CharField(default="New Chat", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
